### ISSUE TITLE
update packaged (cached) data to be spring run

### ISSUE THREAD

**Issue by ergz** [CVPIA-OSC/springRunDSM#1]
Update all of the data internal to be spring run data:
* load_baseline_data - has items that need to switched over to SR
* data-raw/cache-data - has data that may need to be changed based on the definition in the original spring run model

**Comment by ErinCain** [comment]
In load_baseline_data I:
- switched fr_spawn -> sr_spawn
- switched fr_fry -> sr_fry
- switched fr_juv -> fr_juv
- Added spring_run_pools 

In cache-data:
- Verified spring seeds is correct
- Changed proportion_hatchery to reflect original spring model 
- Changed month_return_proportion  to the 4 spring months with proportions from original spring model 
- Changed adult_harvest_rate based on cvpiaDATA misc_data$A.HARV (all values for spring all 0)
- Changed natural_adult_removal_rate based on cvpiaDATA misc_data$prop.nat.remov
- Changed hatchery_allocation based on cvpiaData  misc_data$hatch.alloc

Questions: 
- cvpiaDATA has a spring run specific has_spring_run data. I am not sure if this is transferred over anywhere or is needed in model. It does not appear to be used in the original model. It seems like it may be important because it specifies which watersheds have spring run fish.
- Do we need to use the theoretical_max_areas.csv (in data-raw/misc)?
